title: <p align="center"> Putri Yemima Sarmaida Sinaga </p>

logo: "/images/fotoyemiima.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume_PutriYemima.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pyemimaa/">LinkedIn</a> |
  <a href="https://github.com/pyemimaa">GitHub</a>
  </p>
  
  <p align="justify">
 I am an undergraduate student of Statistics at Diponegoro University. 
  <br><br>
 Currently, I am engaged in learning data science and machine learning using Python. By studying data science and machine learning, I aim to develop a strong foundation in these fields and apply them to solve real-world problems and make data-driven decisions.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
