title: <p align="center"> Putri Yemima Sarmaida Sinaga </p>

logo: "/images/pasfot.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cvyemima.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pyemimaa/">LinkedIn</a> |
  <a href="https://github.com/pyemimaa">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing Bachelor degree in Statistics at Science and Mathematics Faculty, Diponegoro University.
  <br><br>
  I am currently learning data science and machine learning with Python.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
