title: <p align="center"> Putri Yemima Sarmaida Sinaga </p>

logo: "/images/pasfot.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/cvyemima.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pyemimaa/">LinkedIn</a> |
  <a href="https://github.com/pyemimaa">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing Bachelor degree in Statistics at Science and Mathematics Faculty, Diponegoro University. Currently, I am engaged in learning data science and machine learning using Python. This educational pursuit involves gaining knowledge and practical skills in utilizing Python programming language for data analysis, statistical modeling, and machine learning algorithms. By studying data science and machine learning, I aim to develop a strong foundation in these fields and apply them to solve real-world problems and make data-driven decisions.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
