title: <p align="center"> Putri Yemima Sarmaida Sinaga </p>

logo: "/images/fotoyemiima.png?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_PutriYemima.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pyemimaa/">LinkedIn</a> |
  <a href="https://github.com/pyemimaa">GitHub</a>
  </p>
  
  <p align="justify">
 A recent graduate in Statistics from Diponegoro University with a keen interest in data analysis. 
  <br><br>
 I’m eager to apply my knowledge and analytical skills in a real-world setting, seeking an opportunity to contribute to an organization's data-driven decision-making process, and make a meaningful impact.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
